services:
  db:
    image: postgres:latest
    container_name: postgres-db-analytics
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ANALYTICS
    ports:
      - "55433:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - postgres-net
    restart: always

networks:
  postgres-net:
    driver: bridge
  default:
    name: shared-network
    external: true