spring:
  datasource:
    url: jdbc:postgresql://peopleanalytics.postgres.database.azure.com:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
consumer:
  event:
    connection-string: ${EVENT_CONNECTION_STRING}
  topic:
    name: corporateorganization
  subscription:
    name: analytics
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}