server:
  port: 8082
spring:
  data:
    rest:
      base-path: /none
      detection-strategy: annotated
  application:
    name: mic-analytics
  mvc:
    servlet:
      path: /analytics
  datasource:
    url: jdbc:postgresql://localhost:55433/ANALYTICS
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    #show-sql: true
    format_sql: true
    properties:
      hibernate:
        format_sql: true

  jms:
    broker-url: ${SPRING_JMS_BROKER_URL}
    user: ${SPRING_JMS_USER}
    password: ${SPRING_JMS_PASSWORD}
consumer:
  event:
    host: ${CONSUMER_ARTEMIS_HOST:localhost}
    port: ${CONSUMER_ARTEMIS_PORT:6616}
    user: ${CONSUMER_ARTEMIS_USER:admin}
    password: ${CONSUMER_ARTEMIS_PASSWORD:admin}
  topic:
    name: ${CONSUMER_TOPIC_NAME:corporate-organization.employee}
  subscription:
    name: ${CONSUMER_SUBSCRIPTION_NAME:analytics}
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000 # 1h in millisecond
